name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

permissions:
  contents: write  # Explicitly set the permissions for the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: ionic build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # This is the directory where the build output is located